Desenvolvimento WebMobile/sistema/anuncio/urls.py
from django.urls import path
from anuncio.views import ListarAnuncios, CriarAnuncios, EditarAnuncios, DeletarAnuncios #<FotoVeiculo, CriarVeiculos, EditarVeiculos, DeletarVeiculos-->


urlpatterns = [
    path('', ListarAnuncios.as_view(), name='listar-anuncios'),
    path('novo/', CriarAnuncios.as_view(), name='criar-anuncios'),
    path('<int:pk>/', EditarAnuncios.as_view(), name='editar-anuncios'),
    path('deletar/<int:pk>/', DeletarAnuncios.as_view(), name='deletar-anuncios')
]

Desenvolvimento WebMobile/sistema/sistema/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from sistema.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Login.as_view(), name='login'),
    # path('autenticacao-api/', LoginAPI.as_view()),
    path('logout/', Logout.as_view(), name='logout'),
    path('veiculo/', include('veiculo.urls'), name='veiculo'),
    path('anuncio/', include('anuncio.urls'), name='anuncio'),

]

Desenvolvimento WebMobile/sistema/anuncio/models.py
from django.contrib.auth import get_user_model
from django.db import models
from veiculo.models import Veiculo

User = get_user_model()

# Create your models here.
class Anuncio(models.Model):
    data = models.DateTimeField(auto_now_add=True)
    descricao = models.CharField(max_length=200)
    preco = models.DecimalField(decimal_places=2, max_digits=10)

    veiculo = models.ForeignKey(Veiculo, related_name='anuncios', on_delete=models.CASCADE)
    usuario = models.ForeignKey(User, related_name='anuncios_realizados', on_delete=models.CASCADE)

    def __str__(self):
        return '{0} - {1} ({2})'.format(
            self.data,
            self.veiculo,
            self.usuario
        )

Desenvolvimento WebMobile/sistema/veiculo/models.py
from django.db import models
from veiculo.consts import *

class Veiculo(models.Model):
    marca = models.SmallIntegerField(choices=OPCOES_MARCAS)
    modelo = models.CharField(max_length=100)
    ano = models.IntegerField()
    cor = models.SmallIntegerField(choices=OPCOES_CORES)
    foto = models.ImageField(blank=True, null=True, upload_to='veiculo/fotos')
    combustivel = models.SmallIntegerField(choices=OPCOES_COMBUSTIVEIS)

Desenvolvimento WebMobile/sistema/anuncio/forms.py
from django.forms import ModelForm
from anuncio.models import Anuncio

class FormularioAnuncio(ModelForm):

    class Meta:
        model = Anuncio
        exclude = []

Desenvolvimento WebMobile/sistema/anuncio/views.py
from django.shortcuts import render
from anuncio.models import Anuncio
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from anuncio.forms import FormularioAnuncio
# Create your views here.

class ListarAnuncios(LoginRequiredMixin, ListView):
    """
    View para listar anuncios cadastrados.
    """
    
    model = Anuncio
    context_object_name = 'anuncios'
    template_name = 'anuncio/listar.html'


class CriarAnuncios(LoginRequiredMixin, CreateView):
    model = Anuncio
    form_class = FormularioAnuncio
    template_name = 'anuncio/novo.html'
    success_url = reverse_lazy('listar-anuncios')


class EditarAnuncios(LoginRequiredMixin, UpdateView):
    model = Anuncio
    form_class = FormularioAnuncio
    template_name = 'anuncio/editar.html'
    success_url = reverse_lazy('listar-anuncios')


class DeletarAnuncios(LoginRequiredMixin, DeleteView):
    model = Anuncio
    template_name = 'anuncio/deletar.html'
    success_url = reverse_lazy('listar-anuncios')

Desenvolvimento WebMobile/sistema/templates/anuncio/deletar.html
{% extends '../base.html' %}

{% block navbar %}
  {% include 'components/navbar.html' %}
{% endblock %}

{% block title %}Deletar Anúncio{% endblock %}

{% block list %}
<div class="container mt-5">
    <h2 class="mb-4">Deletar Anúncio</h2>
    <form action="{% url 'deletar-anuncios' anuncio.pk%}" method="post" enctype="multipart/form-data"> 
        {% csrf_token %}
        <center>
            <div class="alert alert-danger" role="alert">
                <p>Tem certeza que deseja excluir o anúncio "{{object}}"?</p>
            </div>

            <input type="submit" value="Confirmar" class="btn btn-danger" />
        </center>
        
    </form>
</div>
{% endblock %}

{% block footer %}
  {% include 'components/footer.html' %}
{% endblock %}

Desenvolvimento WebMobile/sistema/templates/anuncio/editar.html
{% extends '../base.html' %}

{% block navbar %}
  {% include 'components/navbar.html' %}
{% endblock %}

{% block title %}Editar Anúncio{% endblock %}

{% block list %}
<div class="container mt-5">
    <h2 class="mb-4">Editar Anúncio</h2>
    <form action="{% url 'editar-anuncios' anuncio.pk %}" method="post" enctype="multipart/form-data"> 
        {% csrf_token %}
        
        <div class="col-md-6">

            
            <div class="col-md-6 mb-3">
                <label for="id_veiculo" class="form-label">Veículo:</label>
                {{ anuncio.veiculo.modelo }}
                <input type="hidden" name="veiculo" value="{{ anuncio.veiculo.id }}">
            </div>
            
            <div class="col-md-6 mb-3">
                <label for="id_usuario" class="form-label">Anunciante:</label>
                {{ anuncio.usuario }}
                <input type="hidden" name="usuario" value="{{ anuncio.usuario.id }}">
            </div>

            <div class="col-md-6 mb-3">
                <label for="id_preco" class="form-label">Preço</label>
                {{ form.preco }}
            </div>


            <div class="col-md-6 mb-3">
                <label for="id_descricao" class="form-label">Descrição</label>
                {{ form.descricao }}
            </div>
        </div>

        <div class="row">
            <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary me-2">Salvar Alterações</button>
                <a href="{% url 'listar-anuncios' %}" class="btn btn-danger">Cancelar</a>
            </div>
        </div>

        
    </form>
</div>
{% endblock %}

{% block footer %}
  {% include 'components/footer.html' %}
{% endblock %}

Desenvolvimento WebMobile/sistema/templates/anuncio/listar.html
{% extends '../base.html' %}

{% block navbar %}
<nav class="navbar navbar-expand-lg bg-primary text-white">
  <div class="container-fluid">
      <a class="navbar-brand text-white" href="/veiculo/">Listagem de Veiculos</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
              <a class="nav-link active text-white" aria-current="page" href="/anuncio/novo/">Adicionar Anúncio</a>
              <a class="nav-link text-white" href="/logout/">Sair</a>
              <!-- <a class="nav-link disabled" aria-disabled="true">Disabled</a>-->
          </div>
      </div>
  </div>
</nav>
{% endblock %}

{% block title %}Listagem{% endblock %}

<!-- Testando o tamanho da lista de anúncios -->
<p>Total de anúncios: {{ anuncios|length }}</p>

<!-- Testando a impressão de todos os anúncios -->
<pre>{{ veiculos }}</pre>

{% block list %}
  <div class="div-lista">
    
    <div class="row">
        <h3>Listando o(s) {{anuncios|length}} anúncio(s):</h3>
      {% for a in anuncios %}  <!-- Corrigido para anuncios -->
      
        <div class="card" style="width: 18rem; margin: 10px;">
          
          <h5>Anuncio {{ a.veiculo.get_marca_display }} - {{  a.veiculo.modelo  }} {{ a.veiculo.ano}}</h5>
          <img class="card-img-top" src="{{ a.veiculo.foto.url }}" alt="{{ a.veiculo.modelo }}">
          
          <div class="card-body">
            <p class="card-text">Descrição: {{  a.descricao }}</p>
            <p class="card-text">Preço: R${{ a.preco }}</p>
            <p class="card-text">Cor: {{ a.veiculo.get_cor_display }}</p>
            <p class="card-text">Combustivel: {{ a.veiculo.get_combustivel_display }}</p>
            <p class="card-text">Anunciante: {{ a.usuario }}</p>
            
            <a href="/anuncio/{{a.id}}" class="btn btn-primary">Editar</a>
            <a href="/anuncio/deletar/{{a.id}}" class="btn btn-danger">Deletar</a>
           
          </div> 
        </div>
      {% empty %}
        <p>Não há anúncios disponíveis no momento.</p>
      {% endfor %}
    </div>
  </div>
{% endblock %}

<!--{% block footer %}
  {% include 'components/footer.html' %}
{% endblock %}
-->

Desenvolvimento WebMobile/sistema/templates/anuncio/novo.html
{% extends '../base.html' %}

{% block navbar %}
  {% include 'components/navbar.html' %}
{% endblock %}

{% block title %}Criar Anúncio{% endblock %}

{% block list %}
<div class="container mt-5">
    <h2 class="mb-4">Criar Novo Anúncio</h2>
    <form action="{% url 'criar-anuncios' %}" method="post" enctype="multipart/form-data"> 
        {% csrf_token %}
        
        <div class="col-md-6">
            <div class="col-md-6 mb-3">
                <label for="id_veiculo" class="form-label">Veículo</label>
                <select name="veiculo" id="id_veiculo" class="form-select">
                    {% for veiculo in form.veiculo.field.queryset %}
                        {% if veiculo.anuncios.count == 0 %}
                            <option value="{{ veiculo.id }}">{{ veiculo.modelo }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </div>
            

            <div class="col-md-6 mb-3">
                <label for="id_preco" class="form-label">Preço</label>
                {{ form.preco }}
            </div>


            <div class="col-md-6 mb-3">
                <label for="id_descricao" class="form-label">Descrição</label>
                {{ form.descricao }}
            </div>

            <div class="col-md-6 mb-3">
                <label for="id_usuario" class="form-label">Anunciante</label>
                {{ form.usuario }}
            </div>
            
            <br>
            
            <div class="row">
                <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary me-2">Criar Anúncio</button>
                    <a href="{% url 'listar-anuncios' %}" class="btn btn-danger">Cancelar</a>
                </div>
            </div>
            
        </div>


       
    </form>
</div>
{% endblock %}